### ISSUE TITLE
Bug - Crashing on incorrect field in login screen

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#2]
**Summary:** 
Crashing on incorrect field in login screen.

**Description:**
If you hit the "log in" button with an invalid email address and password the app will crash.

**Severity:** 
High. If the user incorrectly types their password, they should be prompted to re-enter their information.

**Stack Trace:**
```
2021-12-03 13:07:15.847 1625-6246/? W/sb.v.u.LiteSuggestSourc: On-device lite suggest model loading error.
    java.io.IOException: Wrong index file: /data/user/0/com.google.android.googlequicksearchbox/files/web_suggest_model/index.bin
        at com.google.cc.b.a.c.<init>(PG:5)
        at com.google.android.apps.gsa.staticplugins.searchboxroot.features.n.c.a.run(PG:3)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at com.google.android.apps.gsa.shared.util.c.a.e.run(PG:2)
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1)
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
        at com.google.android.apps.gsa.shared.util.c.a.l.run(PG:5)
     Caused by: java.io.FileNotFoundException: /data/user/0/com.google.android.googlequicksearchbox/files/web_suggest_model/index.bin: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:492)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152)
        at com.google.cc.b.a.c.<init>(PG:1)
        at com.google.android.apps.gsa.staticplugins.searchboxroot.features.n.c.a.run(PG:3) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at com.google.android.apps.gsa.shared.util.c.a.e.run(PG:2) 
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1) 
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
        at com.google.android.apps.gsa.shared.util.c.a.l.run(PG:5) 
     Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:254)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:166)
        at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7542)
        at libcore.io.IoBridge.open(IoBridge.java:478)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:289) 
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:152) 
        at com.google.cc.b.a.c.<init>(PG:1) 
        at com.google.android.apps.gsa.staticplugins.searchboxroot.features.n.c.a.run(PG:3) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at com.google.android.apps.gsa.shared.util.c.a.e.run(PG:2) 
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1) 
        at com.google.android.apps.gsa.shared.util.c.a.bi.run(PG:1) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
        at com.google.android.apps.gsa.shared.util.c.a.l.run(PG:5) 
```

**Comment by masranber** [comment]
Fixed! Thanks
