### ISSUE TITLE
Bug - Crashing when navigating to Calendar page

### ISSUE THREAD

**Issue by speters217** [masranber/MaintenanceBuddy#3]
**Summary:** 
Crashing when navigating to the Calendar page.

**Description:**
When the "Calendar" button is clicked at the bottom of the page, the app immediately crashes.

**Severity:** 
High. I assume the Calendar button has a lot of functionality behind it that is currently inaccessible.

**Stack Trace:**
```
2021-12-03 13:12:10.963 6625-6625/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.maintenancebuddy, PID: 6625
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.example.maintenancebuddy.data.model.UserProfile com.example.maintenancebuddy.data.UserRepository.getCurrentUser()' on a null object reference
        at com.example.maintenancebuddy.ui.calendar.MaintenanceCalendarFragment.onCreateView(MaintenanceCalendarFragment.java:56)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2106)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:2002)
        at androidx.fragment.app.FragmentManager$5.run(FragmentManager.java:524)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by masranber** [comment]
Fixed! Thanks
